server:
    ports:
        http: 8070
    port: 8097
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: 123456
        keyStoreType: PKCS12
        keyAlias: tomcat
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:9091/eureka/
        lease:
            duration: 5
spring:
    application:
        name: web-socket-service
    cache:
        type: redis
        redis:
            port: 6379
            host: localhost