intentNames: Knowledge,Comprehension,Application,Analysis,Synthesis,Evaluation
htmlTags: title,h1,h2,h3,h4,h5,h6,p
htmlTagScores: 45,35,30,25,20,15,10,5
server:
  port: 8098
spring:
  data:
    neo4j:
      password: neo4j@123
      username: neo4j