server:
  port: 8096

spring:
  data:
    neo4j:
      username: neo4j
      password: neo4j@123
    mongodb:
      database: QuestionStore
      host: localhost
      port: 27017
  cache:
    type: redis
    redis:
      port: 6379
      host: localhost


